---

- name: Ensure pip is installed
  apt:
    name: python-pip
    state: present
  become: yes

- name: Install supervisor
  pip:
    name: supervisor
    state: present
    version: "{{ supervisor_version }}"
  when: supervisor_version != 'latest'

- name: Install supervisor
  pip:
    name: supervisor
    state: present
  become: yes
  when: supervisor_version == 'latest'

- name: Set upervisor log directory
  file:
    path: "{{ supervisor_log_dir }}"
    state: directory
    mode: 0755
  become: yes

- name: Ensure supervisor config paths are present
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  with_items:
    - "{{ supervisor_conf_dir }}"
    - "{{ supervisor_conf_dir }}/conf.d"
  become: yes
