---

- name: Copy default supervisor config
  template:
    src: supervisord.conf.j2
    dest: "{{ supervisor_conf_dir }}/supervisord.conf"
    mode: 0644
  become: yes
  #notify: Restart supervisor

- name: Copy program configs for supervisor
  template:
    src: program.conf.j2
    dest: "{{ supervisor_conf_dir }}/conf.d/{{ item.name }}.conf"
    mode: 0644
    owner: root
    group: root
  with_items:
    - "{{ supervisor_programs }}"
  become: yes
  #notify: Restart supervisor

- name: Copy supervisor init file (for non systemd systems)
  template:
    src: supervisord.init.j2
    dest: /etc/init.d/supervisord
    owner: root
    group: root
    mode: 0755
  when: "ansible_service_mgr != 'systemd'"
  become: yes

- name: Copy supervisor unit file (for systemd systems)
  template:
    src: supervisord.unit.j2
    dest: /etc/systemd/system/supervisord.service
    owner: root
    group: root
    mode: 0755
  when: "ansible_service_mgr == 'systemd'"
  become: yes
  #notify: Restart supervisor
